---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ruby:
    name: 'Ruby ${{ matrix.ruby }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libaugeas-dev
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
